name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/bg-bottom-hero.png
    - assets/page-1/images/voucher-2.png
    - assets/page-1/images/voucher5000listrik-1.png
    - assets/page-1/images/icon-menu-listrik.png
    - assets/page-1/images/voucher2000provider-1.png
    - assets/page-1/images/bg-dot-2.png
    - assets/page-1/images/voucher-6.png
    - assets/page-1/images/bg-round.png
    - assets/page-1/images/icon-menu-handphone.png
    - assets/page-1/images/voucher-3.png
    - assets/page-1/images/bg-round-dqx.png
    - assets/page-1/images/ellipse-1.png
    - assets/page-1/images/voucher2000listrik-1.png
    - assets/page-1/images/bg-round-gZk.png
    - assets/page-1/images/bg-round-6BY.png
    - assets/page-1/images/promo-banner-1.png
    - assets/page-1/images/bg-round-6t6.png
    - assets/page-1/images/bg-bottom-hero-vPg.png
    - assets/page-1/images/bg-dot-2-eyt.png
    - assets/page-1/images/bg-bottom-hero-rFG.png
    - assets/page-1/images/bg-round-be6.png
    - assets/page-1/images/voucher10000provider-1.png
    - assets/page-1/images/bg-dot-1.png
    - assets/page-1/images/bg-round-v3x.png
    - assets/page-1/images/bg-bottom-hero-PjU.png
    - assets/page-1/images/icon-coin.png
    - assets/page-1/images/bg-tree.png
    - assets/page-1/images/coin-1.png
    - assets/page-1/images/bg-dot-1-H8a.png
    - assets/page-1/images/bg-tree-cRk.png
    - assets/page-1/images/icon-listrik.png
    - assets/page-1/images/ellipse-1-iJ2.png
    - assets/page-1/images/icons8-featurephone-100-1-1.png
    - assets/page-1/images/bg-tree-rb8.png
    - assets/page-1/images/bg-dot-2-z5c.png
    - assets/page-1/images/bg-dot-1-7US.png
    - assets/page-1/images/voucher5000provider-1.png
    - assets/page-1/images/bg-dot-2-MMQ.png
    - assets/page-1/images/bg-tree-RFC.png
    - assets/page-1/images/auto-group-muse.png
    - assets/page-1/images/bg-dot-2-7QA.png
    - assets/page-1/images/bg-bottom-hero-Wj8.png
    - assets/page-1/images/bg-dot-1-rnz.png
    - assets/page-1/images/bg-round-RbC.png
    - assets/page-1/images/icon-hp.png
    - assets/page-1/images/ellipse-2.png
    - assets/page-1/images/bg-dot-2-gzr.png
    - assets/page-1/images/bg-dot-1-MvW.png
    - assets/page-1/images/ellipse-2-BSv.png
    - assets/page-1/images/bg-bottom-hero-uLr.png
    - assets/page-1/images/bg-bottom-hero-THp.png
    - assets/page-1/images/bg-dot-1-PhG.png
    - assets/page-1/images/icon-ketentuan.png
    - assets/page-1/images/bg-dot-2-SWS.png
    - assets/page-1/images/bg-dot-2-kGE.png
    - assets/page-1/images/bg-tree-1mp.png
    - assets/page-1/images/bg-dot-1-qsk.png
    - assets/page-1/images/voucher-5.png
    - assets/page-1/images/bg-dot-1-wre.png
    - assets/page-1/images/bg-dot-1-CCE.png
    - assets/page-1/images/ellipse-2-agW.png
    - assets/page-1/images/voucher-4.png
    - assets/page-1/images/bg-tree-rJr.png
    - assets/page-1/images/icon-listrik-qyQ.png
    - assets/page-1/images/bg-bottom-hero-5SN.png
    - assets/page-1/images/icon-search.png
    - assets/page-1/images/bg-bottom-hero-TTL.png
    - assets/page-1/images/bg-tree-pHt.png
    - assets/page-1/images/bg-dot-2-54i.png
    - assets/page-1/images/voucher-1.png
    - assets/page-1/images/icon-menu-voucher.png
    - assets/page-1/images/voucher10000listrik-1.png
    - assets/page-1/images/icon-kebijakan.png
    - assets/page-1/images/ellipse-1-jTC.png
    - assets/page-1/images/bg-round-bve.png
    - assets/page-1/images/bg-tree-dTL.png
    - assets/page-1/images/bg-bottom-hero-.png
    - assets/page-1/images/bg-tree-agE.png
    - assets/page-1/images/bg-dot-1-hWW.png
    - assets/page-1/images/bg-round-fSe.png
    - assets/page-1/images/bg-dot-2-bEv.png
    - assets/page-1/images/bg-dot-2-1dx.png
    - assets/page-1/images/icon-top-up.png
    - assets/page-1/images/icon-coin-Kst.png
    - assets/page-1/images/bg-dot-1-5pz.png
    - assets/page-1/images/bg-bottom-hero-fxa.png
    - assets/page-1/images/bg-tree-7Gi.png
    - assets/page-1/images/bg-tree-kRL.png
    - assets/page-1/images/bg-round-dAW.png
    - assets/page-1/images/icon-home.png
    - assets/page-1/images/icon-log-out.png
    - assets/page-1/images/icon-person.png
    - assets/page-1/images/icon-settings.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
